# -*- coding: utf-8 -*-
"""hamit_the5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WMw1QGgxyUUhf7AuAiMA1bpfmaKVu_EQ
"""

#Hamit Kartal 28404
myBook = open('book.txt', 'r', encoding='latin-1')



def levenshtein(str1, str2):
  size_x = len(str1) + 1
  size_y = len(str2) + 1
  matrix = []
  for i in range(size_x):
    temp = [0]*size_y
    matrix.append(temp)
  for i in range(size_x):
    matrix[i][0] = i
  for i in range(size_y):
    matrix[0][i] = i
  for x in range(1, size_x):
      for y in range(1, size_y):
          if str1[x-1] == str2[y-1]:
              matrix [x][y] = min(matrix[x-1][y] + 1, matrix[x-1][y-1], matrix[x][y-1] + 1)
          else:
            matrix [x][y] = min(matrix[x-1][y] + 1, matrix[x-1][y-1] + 1, matrix[x][y-1] + 1)
  return(matrix[size_x - 1][size_y - 1])



dictionary = {}
for line in myBook:
  line = line.strip()
  line = line.split(' ')
  for word in line:
    word = word.strip('.,!?:;"').lower()
    if word in dictionary:
      dictionary[word] += 1
    else:
      dictionary[word] = 1

str1 = input('Please enter the word/words you want to check: ')
while str1 != 'exit()':
  str1 = str1.split(' ')
  str2 = ''
  for a in str1:
    if a in dictionary.keys():
      str2 += a + ' '
    else:
      differenceDictionary = {}
      for b in dictionary.keys():
        difference = levenshtein(a,b)
        differenceDictionary[b] = difference
      x = []
      for z in differenceDictionary.values():
        x.append(z)
      minDifferenceOccur = x.count(min(differenceDictionary.values()))
      if minDifferenceOccur == 1:
        minDifference = min(differenceDictionary.values())
        for key, value in differenceDictionary.items():
          if minDifference == value:
            correctWord = key
            break
        str2 += correctWord + ' '
      elif minDifferenceOccur > 1:
        minDifference = min(differenceDictionary.values())
        possibleOnes = {}
        for key, value in differenceDictionary.items():
          if value == minDifference:
            possibleOnes[key] = dictionary[key]
        u = max(possibleOnes.values())
        x2 = []
        for z2 in possibleOnes.values():
          x2.append(z2)
        k = x2.count(u)
        if k == 1:
          for key, value in possibleOnes.items():
            if value == u:
              str2 += key + ' '
              break
        elif k > 1:
          possibleOnesList = []
          for key, value in possibleOnes.items():
            if value == u:
              possibleOnesList.append(key)
          possibleOnesList.sort()
          str2 += possibleOnesList[0] + ' '
  str2 = str2.strip()
  myList2 = str2.split(' ')
  if str1 == myList2:
    print('String you entered is correctly written!')
  elif str1 != myList2:
    print('Did you mean:', str2)
  str1 = input('Please enter the word/words you want to check: ')


print('See you next time...')

myBook.close()