# -*- coding: utf-8 -*-
"""hamit_the2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEHy6chYRtbfc9mGEQTTpQV9fdOCKobz
"""

term = input('Please enter your current term: ')
if term.isdigit():
  term = int(term)
  if 1 < term:
    credit = input('Please enter the total credits you earned before: ')
    if credit.isdigit():
      credit = int(credit)
      if (term == 2 and 34 > credit) or (term == 3 and 49 > credit) or (term > 3 and 58 > credit):
        print('Your Erasmus score cannot be calculated before you took the required amount of credits.')
      elif (2 == term and 34 <= credit) or (term == 3 and 49 <= credit) or (term > 3 and 58 <= credit):
        SPS101 = input('Please enter the SPS101 letter grade equivalents: ')
        if SPS101[0].isalpha() and SPS101[-1].isdigit() and SPS101.count(':') == 1 + SPS101.count(';'):
          SPS101 = SPS101.upper()
          SPS101 += ';'
          AL102 = input('Please enter the AL102 letter grade equivalents: ')
          if AL102[0].isalpha() and AL102[-1].isdigit() and AL102.count(':') == 1 + AL102.count(';'):
            AL102 = AL102.upper()
            AL102 += ';'
            letter_grades = input('Please enter your SPS101 and AL102 letter grades: ')
            letter_grades = letter_grades.upper()
            if letter_grades.count(',') == 1 and letter_grades[0] != ',' and letter_grades[-1] != ',':
              SPSlettergrade = letter_grades[:letter_grades.find(',')]
              SPSlettergrade += ':'
              ALlettergrade = letter_grades[letter_grades.find(',') + 1:]
              if ALlettergrade == '-':
                ALlettergrade = 'C:'
                if SPSlettergrade not in SPS101:
                  print("Your SPS101 letter grade couldn't be found in point-scale.")
                elif ALlettergrade not in AL102:
                  print("Your AL102 letter grade couldn't be found in point-scale.")
                elif SPSlettergrade in SPS101 and ALlettergrade in AL102:
                  indexsps = SPS101.find(SPSlettergrade)
                  lengthsps = len(SPSlettergrade)
                  SPSpointgrade = SPS101[indexsps + lengthsps : SPS101.find(';',indexsps)]
                  indexal = AL102.find(ALlettergrade)
                  lengthal = len(ALlettergrade)
                  ALpointgrade = AL102[indexal + lengthal : AL102.find(';',indexal)]
                  SPSpointgrade = float(SPSpointgrade)
                  ALpointgrade = float(ALpointgrade)
                  GPA = float(input('Please enter your current GPA: '))
                  if 0 <= GPA < 2.2:
                    print('Your GPA needs to be at least 2.2.')
                  elif 0 > GPA or 4 < GPA:
                    print('Your GPA needs to be in between 0-4.')
                  else:
                    English_score = (SPSpointgrade * 0.4) + (ALpointgrade * 0.6)
                    Erasmus_score = (English_score * 0.5) + (GPA * 25 * 0.5)
                    print('Your final Erasmus score is, ' + str(Erasmus_score) + '.')
              #Al harf notu '-' olarak girilmemişse koşulu aşağıdan devam ediyor
              else:
                ALlettergrade += ':'
                if SPSlettergrade not in SPS101:
                  print("Your SPS101 letter grade couldn't be found in point-scale.")
                elif ALlettergrade not in AL102:
                  print("Your AL102 letter grade couldn't be found in point-scale.")
                elif SPSlettergrade in SPS101 and ALlettergrade in AL102:
                  indexsps = SPS101.find(SPSlettergrade)
                  lengthsps = len(SPSlettergrade)
                  SPSpointgrade = SPS101[indexsps + lengthsps : SPS101.find(';',indexsps)]
                  indexal = AL102.find(ALlettergrade)
                  lengthal = len(ALlettergrade)
                  ALpointgrade = AL102[indexal + lengthal : AL102.find(';',indexal)]
                  SPSpointgrade = float(SPSpointgrade)
                  ALpointgrade = float(ALpointgrade)
                  GPA = float(input('Please enter your current GPA: '))
                  if 0 <= GPA < 2.2:
                    print('Your GPA needs to be at least 2.2.')
                  elif 0 > GPA or 4 < GPA:
                    print('Your GPA needs to be in between 0-4.')
                  else:
                    English_score = (SPSpointgrade * 0.4) + (ALpointgrade * 0.6)
                    Erasmus_score = (English_score * 0.5) + (GPA * 25 * 0.5)
                    print('Your final Erasmus score is, ' + str(Erasmus_score) + '.')
            else:
              print('Invalid input for SPS101 and AL102 letter grades.') 
          else:
            print('Invalid input for AL102 letter grade sequence.')
        else:
          print('Invalid input for SPS101 letter grade sequence.')
      else:
        print('Invalid input for the credits earned before.')
    else:
      print('Invalid input for the credits earned before.')
  elif 1 == term:
    print('Your Erasmus score cannot be calculated before the 2nd term.')
  else:
    print('Invalid input for the current term.')
else:
  print('Invalid input for the current term.')