# -*- coding: utf-8 -*-
"""hamit_the4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OOy1zPh0BltiKjQ-J4K_afNj8Xx58qoK
"""

# Hamit Kartal


#def isAlphaNumeric(inp):
 # for i in inp:
  #  if not(48 <= ord(i) <= 57) and not(65 <= ord(i) <= 90) and not(97 <= ord(i) <= 122):
  #    return False
  #return True

def isEnglish(inp):
  for i in inp:
    if not(65 <= ord(i) <= 90) and not(97 <= ord(i) <= 122):
      return False
  return True



def getPartyName(a,b):
  inp = input('Please enter the name of the ' + a + ' party: ').capitalize()
  y = False 
  while y == False:
    while ' ' in inp or isEnglish(inp[0]) == False:
      inp = input('Invalid party name. Please enter again: ').capitalize()
    while inp in b:
      inp = input(inp + ' already exists. Please enter again: ').capitalize()
    if ' ' in inp or isEnglish(inp[0]) == False:
      y = False
    else:
      y = True
  b.append(inp)



#def getMenuOption():
 # print('Menu:\n1. Enter results for a new city.\n2. Change results of a specific city.\n3. Show current results.\n4. Exit.')
  #print()
  #option = input('Select one of the options (1-4): ')
  #okay = ['1', '2', '3', '4']
  #while option not in okay:
   # option = input('You have entered an invalid input for menu selection. Please enter again: ')
  #return option



def getMenuOption():
  print('\nMenu:\n1. Enter results for a new city.\n2. Change results of a specific city.\n3. Show current results.\n4. Exit.')
  option = input('\nSelect one of the options (1-4): ')
  while not (option == '1' or option == '2' or option == '3' or option == '4'):
    option = input('You have entered an invalid input for menu selection. Please enter again: ')
  return option
  

def getNewResults(a):
  inp = input('Please enter the name of the city: ').capitalize()
  while not isEnglish(inp):
    inp = input('Invalid city name. Please enter again: ').capitalize()
  if inp in a:
    print('You cannot enter ', inp, ' since this city has already been entered. If you want you can update the results of this city by using the 2nd menu option.')
  else:
    a.append(inp)
    inp2 = input('Please enter results for ' + inp + ': ')
    inp2 = inp2.split('-')
    for i in range(len(inp2)):
      inp2[i] = float(inp2[i])
    a.append(inp2)
    return a
    


def changeResults(a):
  inp = input('Please enter the name of the city: ').capitalize()
  while isEnglish(inp) == False:
    inp = input('Invalid city name. Please enter again: ').capitalize()
  if inp not in a:
    print('You cannot change the result of ', inp, ' since no result has been entered for this city yet.')
  else:
    inp2 = input('Please enter results for ' + inp + ': ')
    inp2 = inp2.split('-')
    for i in range(0,len(inp2)):
      inp2[i] = float(inp2[i])
    indx = a.index(inp)
    a.pop(indx+1)
    a.insert(indx+1,inp2)
    return a


def showResults(a,b):  
  if len(a) == 0:
    print('No information available yet...')
  elif len(a) > 0:
    for indx in range(0,len(a),2):
      maxElem = max(a[indx+1])
      indxx2 = a[indx+1].index(maxElem)
      if a[indx+1].count(maxElem) == 1:
        print(a[indx], a[indx+1][0], a[indx+1][1], a[indx+1][2], '-->', b[indxx2], 'is leading')
      elif a[indx+1].count(maxElem) == 3:
        print(a[indx], a[indx+1][0], a[indx+1][1], a[indx+1][2], '-->', b[0], b[1], b[2], 'are leading')
      elif a[indx+1].count(maxElem) == 2:
        indxx3 = a[indx+1].index(maxElem,indxx2+1)
        print(a[indx], a[indx+1][0], a[indx+1][1], a[indx+1][2], '-->', b[indxx2], b[indxx3], 'are leading')


#############################
## DO NOT MODIFY THIS CELL ##
## JUST RUN THIS WHEN YOU COMPLETE YOUR FUNCTIONS ##
#############################
####### MAIN PROGRAM ########
#############################

print("Welcome to this virtual local elections Python program.\n")

# get the names of the parties
partyNames = []                               # stores the valid party names
promptData = ["first", "second", "third"]
for i in range(3):
  getPartyName(promptData[i], partyNames)

# dataset variable initialization
citiesAndResults = []                         # stores the city-results information

# display the menu, get user's option, and process accordingly
option = getMenuOption()
while option != "4":
  if option == "1":
    getNewResults(citiesAndResults)           # function call to update citiesAndResults with a new city
  elif option == "2":
   changeResults(citiesAndResults)            # function call to update citiesAndResults for an existing city
  elif option == "3":
    showResults(citiesAndResults, partyNames) # function call to display current election results
  option = getMenuOption()

print("**********\nTerminating, good bye dear citizen!!! Do not forget to vote in elections :)")