# -*- coding: utf-8 -*-
"""hamit_quiz5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15eUj2_ok6ugnkpCyh4cPWTFdfu45lutJ
"""

#id_List = [123456789, 435090235, 656589898]
#family_List = [[680375920,325781048],[354983498],[3460754,469645,537968,537964]]
threshold = int(input('Please enter the integer: '))
y = len(id_List)
for x in range(y):
  summ = 1 + len(family_List[x])
  if summ > threshold:
    print(id_List[x])