# -*- coding: utf-8 -*-
"""hamit_q5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MQCEhtH475YcwjpxeuJjn_ljp0PJ3QZq
"""

#from google.colab import files
#myFile = files.upload()

matches = open('scores.txt')

dic = {}
informations = []

for line in matches:
  line = line.strip()
  infos = line.split(' ')
  firstTeam = infos[0]
  secondTeam = infos[3]
  informations.append(infos)
  if (firstTeam not in dic) and (secondTeam not in dic):
    dic[firstTeam] = 0
    dic[secondTeam] = 0
  elif (firstTeam not in dic) and (secondTeam in dic):
    dic[firstTeam] = 0
  elif (firstTeam in dic) and (secondTeam not in dic):
    dic[secondTeam] = 0

  
for match in informations:
  ilkTakim = match[0]
  ikinciTakim = match[3]
  ilkTakimSkor = match[1]
  ikinciTakimSkor = match[2]
  if ilkTakimSkor > ikinciTakimSkor:
    dic[ilkTakim] += 3
  elif ilkTakimSkor == ikinciTakimSkor:
    dic[ilkTakim] += 1
    dic[ikinciTakim] += 1
  elif ilkTakimSkor < ikinciTakimSkor:
    dic[ikinciTakim] += 3



#print(dic) #ödevin son halinde siliceksin


print('TeamName\tPTS')
size = len(dic.keys())
for i in range(size):
  for key, value in dic.items():
    puan = max(dic.values())
    for key, value in dic.items():
      if value == puan:
        takim = key
    print(takim, '\t', puan)
    dic.pop(takim)
    break


matches.close()