# -*- coding: utf-8 -*-
"""hamit_q2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GFLDBqHE0QqUrEy6qzpM06h8G9tBCQTQ
"""

#Hamit Kartal 28404
inp1 = input('Do you have a problem in your life?: ')

if inp1 == 'Yes':
  inp2 = input('Can you do something about it?: ')
  if inp2 == 'Yes':
    print('Then do it')
  elif inp2 == 'No':
    print("Then don't worry")
elif inp1 == 'No':
  print("Then don't worry")