# -*- coding: utf-8 -*-
"""hamit_q4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HDDXBBPpyHsCBLJtE0iaBqJUDf9fl39_
"""

def turing(rowNum, colNum):
  neededLists = matrix[len(matrix)-rowNum:]
  for i in neededLists:
    neededElems = i[len(i)-colNum:]
    for x in neededElems:
      print(x, end=' ')
    print()


rowNum = int(input('Enter rowNum: '))
colNum = int(input('Enter colNum: '))
while (rowNum > len(matrix)) or (colNum > len(matrix[0])):
  print('rowNum and/or colNum is too high!')
  rowNum = int(input('Enter rowNum: '))
  colNum = int(input('Enter colNum: '))

turing(rowNum, colNum)