# -*- coding: utf-8 -*-
"""hamit_q3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ef7Kjjh7LPA2Gs5AGggmS0BqV38VEfZS
"""

#Hamit Kartal 28404
num = int(input('Please enter the number of values to be entered: '))
dictionary = {}
for i in range(num):
  name = input('Please enter a name: ')
  year = int(input('Please enter ' + name + "'s birth year: "))
  dictionary[name] = year
oldest = min(dictionary.values())
for key, value in dictionary.items():
  if oldest == value:
    oldestPerson = key
print('The oldest person is ' + oldestPerson)